### PR TITLE
Improve openvr controller bindings

### LINKED ISSUE #19: Suggestion: VR-interface hotspots/binds
VR games often add inventory-like areas on the player body - waist, wrists, shoulders etc. that player can interact with, or place the items/weapons and later equip them by physically picking them up.

I understand this might be extremely tricky to do in GZDoom environment, so my suggestion is a bit different. 
Instead of making outright physical interaction it might be easier to make sort-of interactive hotspot areas that would invoke a bind (defined by player) when player puts their hand within such area and presses a dedicated button (most probably grip).
It would act akin to those inventory areas in modern VR games, but with much more customability on user part and significantly easier to code on developer part since no actual physical interaction betweween objects needed - just a check whether player hand is within one of those areas when they press grip (or whatever button they assign to it).
IMO would be better to associate rarely used letters with those areas - like YUIOPLKJHGBNM, so that the player would be able to assign their aliases/binds to them for various functions aside from weapon/item equip - they may also be used for more complex aliases, mod specific functions, next/previous inventory/weapon binds, using console comand and anything else normally bound to a button.

Areas I'd suggest:
2 behind each shoulder, 2 on the belt, 2 on the chest, 2 on the wrists, 1 behind lower back. Another good binding place would be touching Left and Right sides of headsets (without pressing the interact/grip button)- I've seen a few games using that kind of interaction for switching vision modes.

### LINKED ISSUE #34: controls not right with valve index
It seems like when i try to set up the controls from the menu, it gives them names it might give an xbox controller's buttons. It uses button names like Pad_Start, Pad_Back, Pad_A, Pad_X, Pad_Y, LShoulder, LTrigger. But I am using a valve index controller. I am not bothered by the names used, but I wonder if this is why I can't get it to work well. When I assign attack/fire to my right knuckle controller's A button, the button is labeled as RShoulder on the game, and so when I press my A button it will fire, but it also causes me to fire when I squeeze the right controller. I was playing Heretic and whenever I press up on my right thumb stick I walk forward correctly, but it also activates my flying item if I have one. I cleared out all the bindings to prevent buttons having multiple functions but I still think this gzdoom port is needing some fix for knuckle controllers.

Also, I can't assign a button to the thumb stick when it is clicked down, because whenever I press the thumb stick in a direction it behaves as though I am clicking it in. I tested my knuckle controller with Steam's software and it shows that I can move the thumb stick all around without the clicking function being activated so this should not be a problem with my controller.

### LINKED ISSUE #42: Valve Index skipping menu options
Using the joystick or touch pad with the index controllers moves up two menu options at a time.

### LINKED ISSUE #55: Oculus Quest 2 button mapping problem
I'm using Oculus Quest 2 over Air Link mainly because questzdoom keeps crashing with all my mods. The problem I'm running into is the buttons are labeled wrong somehow...

So far what I've seen is 
A button on the right controller shows up as Pad_B
B button on the right controller shows up as Pad_Back
Right Stick Button shows up as Pad_Y
Left Stick Button shows up as Pad_X
Y button on left controller shows up as Pad_Start
X button on left controller shows up as Pad_A
The 2 trigger buttons and the left Oculus button can't be rebound.

### LINKED ISSUE #58: [Suggestion] Requesting more button customization and button combo
Some buttons mapping are hardcoded (like trigger buttons) and cannot be mapped to other actions. eg. binding left trigger to alt-fire is not possible. Can we have less buttons mapped through codes and allow us the bindings on them through control settings?

Also QuestZDoom supports off-hand grip + any other button as combo to bind as new buttons. This is especially helpful when using a mod that requires way more action buttons (eg. separate buttons for melee, grenade, fly/swim up/down, inventory left/right, inventory item select, drop weapon/item etc.). Is it possible to add this feature in GZDoomVR? This will essentially double the number of mappable buttons in the controller.

Here's how the key bindings work in QuestZDoom:

Primary Button Functions:

A Button - Open Door / Switch
B Button - Jump
Y Button - Toggle AutoMap
X Button - Unmapped [Delete a button mapping in the menu]
Dominant-Hand Controller - Weapon orientation
Dominant-Hand Thumbstick - left/right Snap turn, up/down weapon change
Dominant-Hand Thumbstick click - Unmapped
Dominant-Hand Trigger - Fire Weapon
Dominant Grip Button - When held down, secondary button functions are available
Off-Hand Controller - Direction of movement (or if configured settings HMD direction is used)
Off-Hand Thumbstick - locomotion / teleport
Off-Hand Trigger - Run
Off-Hand Grip Button - Weapon Stabilization - two handed weapon mode
Off-Hand Thumbstick click - Unmapped

Secondary Button Functions:
Accessed by holding down the dominant hand grip button - All these can be reassigned in the options menu

A Button - Unmapped
B Button - Unmapped
Y Button - Unmapped
X Button - Unmapped
Dominant-Hand Thumbstick click - Unmapped
Dominant-Hand Trigger - Alt Fire Weapon
Off-Hand Trigger - Unmapped
Off-Hand Thumbstick click - Unmapped

### LINKED ISSUE #65: [BUG] Can't stop myself from jumping with the right analog stick on Index
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

Intel 11900k, rtx 3080, 64 gb ddr4-3200, Valve Index

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I feel like there's a better place for this but I can't seem to find much online in the way of fixing this issue. For some reason by default turning with the index controller makes the character jump repeatedly. it's only when push the analog stick to the outermost point in any direction. 

I'm assuming it's a holdover from the Vive controls but I can't figure out how to change it. The steam VR menu just has it listed as analog right (or something along those lines) any attempt to manually change the binds in the settings  just makes things worse, I can't figure out how to delete binds you made by mistake in the menu and I don't really know what commands I should be putting in to edit the ini manually.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play gzdoomvr with index controllers.
2. Push the right analog stick all the way in any direction
3.jump up, jump up and get down.

### Your configuration

```ini
I'm at work right now so I can't access it by it's the default in found right after extracting the game. I'll forward it when I get home if you need it.
```

### Provide a Log

N/A

### LINKED ISSUE #77: [BUG] Cannot bind LTrigger to any action
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

x64 21H2

### Relevant hardware info

Oculus Quest 2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

LTrigger is mapped to +altattack as default, but it does not respond. I tried changing it to +use but it doesn't react either. Other buttons on the controllers seems to work fine.

I discovered this when trying to run Brutal Doom and using the fists. Right clicking the mouse still works for alternate fire, but LTrigger (the trigger on the left VR controller) does not seem to trigger anything, even if manually binding it to +attack or +use or other actions manually in the console or config files. Trying to bind it using the menus does not register when I press LTrigger. The menus are still waiting for a button press. Other controller buttons will register fine.

PS: Would it be possible for GZDoomVR to work with mods that have dual wielding (one weapon in each VR hand)? Or is it only for one weapon/hand?

### Steps to reproduce the behaviour.

1. Run GZDoomVR in SteamVR with Oculus Quest 2 and load any game.
2. Try to change the button for an action. Nothing happens if LTrigger is pressed.
3. Alternatively run `bind LTrigger +attack` in the console or edit config files and see that LTrigger does nothing in the game

### Your configuration

_No response_

### Provide a Log

_No response_

### LINKED ISSUE #78: [BUG] RStickUp and RStickDown not registering correctly
### GZDoom version

_No response_

### Which game are you running with GZDoom?

_No response_

### What Operating System are you using?

_No response_

### Please describe your specific OS version

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

when defining the controls `RStickUp` wrongly registers as `RStickDown` and `RStickDown` registers as `RStickLeft`.

this is with index controllers, but i strongly assume other controllers having the same problem.

### Steps to reproduce the behaviour.

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### PR DESCRIPTION
**Pull request by codeflorist**
This PR improves/fixes the following controller-issues:

- fix: RStickUp and RStickDown not registering correctly on button mapping
- fix: LTrigger/RTrigger not being mappable in menu
- fix: LTrigger/RTrigger firing additional Enter on showing menu in splash screen
- fix: left stick jumping 2 menu-items on up/down instead of 1
- change: mapping of touchpad/stick-presses to lthumb/rthumb instead of pad_x/pad_y
- add: mapping for k_EButton_Axis2 to pad_x/pad_y (usable with steamVR-binding "Right Axis 2 Press" [at least with Index Controller]; unfortunately there is no "Left Axis 2 Press" in steamVR-binding :/)
- add: mapping for k_EButton_Axis3 to joy1/joy2 (unknown if used by any controller at all)
- add: mapping for k_EButton_Axis4 to joy3/joy4 (unknown if used by any controller at all)
- add: mapping for k_EButton_ApplicationMenu (aka k_EButton_IndexController_B) to GK_BACKSPACE in menus (to delete a mapping)
- add: mapping for k_EButton_A to GK_BACK (thus both grip and A are usable for menu-back)
- docs: add info about Index Controller binding in README

it also adds a link to Brutal Doom 64 weapon pack, and the Virtual Tactical Vest to README.

this fixes #78,  fixes #77, fixes #42, fixes #34, fixes #19, fixes #65, possibly fixes #55, partly fixes #58

### CODE REVIEW

**Comment by codeflorist** [comment]
i've added another commit to swap `pad_start` and `pad_back` between controllers.

the reasoning behind this is that `pad_back` is hardcoded in gzdoom to open/close the menu. opening the menu is not an action, that must be able to be performed while moving, so it's better to have it on the off-hand controller, which is used for moving. this frees up the button on the main hand to be bound to actions that _should_ be able to be performed while moving (e.g. jump, crouch, reload, altattack, etc.).

**Comment by hh79** [comment]
Thanks for a PR, it looks fine. I will look into when I am back from vacation next week.

**Comment by Peweyxil** [comment]
Finally, a possible fix for the frustrating Index controller mappings! But it has been forgotten? Or will it be implemented?

**Comment by codeflorist** [comment]
> Finally, a possible fix for the frustrating Index controller mappings! But it has been forgotten? Or will it be implemented?

@Peweyxil i've uploaded a build with my fixes here: https://github.com/codeflorist/gzdoomvr/releases/tag/gvr4.11.3icb

**Comment by Peweyxil** [comment]
> @Peweyxil i've uploaded a build with my fixes here: https://github.com/codeflorist/gzdoomvr/releases/tag/gvr4.11.3icb

Nice! With your build, the Valve Index's left controller's grip and button A both get assigned to "LShoulder" and the right controller's grip and button A get assigned to "RShoulder", so I'm two buttons short of perfection but the frustration is gone and much better gameplay can now be done! :D

**Comment by codeflorist** [comment]
> > @Peweyxil i've uploaded a build with my fixes here: https://github.com/codeflorist/gzdoomvr/releases/tag/gvr4.11.3icb
> 
> Nice! With your build, the Valve Index's left controller's grip and button A both get assigned to "LShoulder" and the right controller's grip and button A get assigned to "RShoulder", so I'm two buttons short of perfection but the frustration is gone and much better gameplay can now be done! :D

@Peweyxil
You can fix this in SteamVR's controller mapping. For reasons only Valve knows, the `A` buttons are mapped to `Grip` instead of `A` by default in legacy bindings.

Also be sure to remove the `Use as Button` mapping from both Thumb Sticks (to avoid firing click-event on moving sticks).

And you can add a `Use as Button` - `Click` binding for `Right Axis 2 Press` to e.g. the right trackpad to get an additional button.

If you can see a community binding from `gameflorist`, you can use that to have all these changes and thus maximum available buttons.

**Comment by Peweyxil** [comment]
Thanks for the additional info! Got it working even better now with the community binding. And of course thanks to Hari for making a VR port of gzdoomvr years ago and then getting it updated all the way to 4.11!

**Pull request merged**
