### PR TITLE
Feature Implementation: Snap Turn

### PR DESCRIPTION
**Pull request by havetc**
As mentionned in my issue #74 , the only option of smooth turn is not very comfortable for some people. I kept the smooth turn as the default in the configuration, but it can easily be turned on in the VR Config menu, and the angle can be edited.
As I thought it didn't took a lot of time to implement, but I kinda forgot to finalize my work until recently.

### CODE REVIEW

**Comment by Si13x** [comment]
Just dropping by real quick to voice my interest in this feature getting merged.  Been playing classic Doom since the original shareware was getting passed around on floppies, and snap turn is honestly the only thing missing from making your wonderful VR conversion perfect.  Many thanks to hh79, havetc, and everyone else who's ever contributed to this project!

**Comment by wyldcrd** [comment]
Does the snap turn have a minimum activation radius ie: a deadzone for turning as some controllers can drift. (I also just like this feature because it makes it harder to just bump the stick a bit and turn 45 degrees)

**Comment by havetc** [comment]
@wyldcrd Good question, I don't know if and how deadzone is implemented at the moment. I didn't change anything related to the deadzone because in my tests I didn't have any trouble with it.
In the `G_AddViewAngleSnap` function I added, I suppose it could be possible to check the absolute value of `yaw` against a threshold in order to add a specific deadzone to snap turn.

**Comment by havetc** [comment]
@hh79 please take a look someday, it's been a while that I implemented this

**Comment by hh79** [comment]
It was finally merged, thanks.

**Pull request merged**
